spring.application.name: unibank-service-unibank-service-sgsn-demo
spring:
  profiles:
    group:
      local:
        - embedded-rabbitmq
        - database-migration
      test:
        - unibank-test
    include:
      - unibank-core
      - unibank-persistence-simple
  cloud:
    vault:
      enabled: false
      kv:
        enabled: false
  jpa:
    show_sql: true
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace
unibank.service.persistence.tenants: 'unibank.components.db.entities'
